### ISSUE TITLE
right mouse button should work by default

### ISSUE THREAD

**Issue by imadsousou** [clearlinux/clr-desktop-defaults#4] opened 2018-12-07 01:49 UTC

**Comment by mrkz** [comment] 2018-12-07 15:50
this should be addressed with the release [V16](https://github.com/clearlinux/clr-desktop-defaults/releases/tag/V16), we just merged this on CLR and should be available shortly.

**Comment by jairglez** [comment] 2018-12-10 18:21
I can confirm the issue is gone on 26730.

**Comment by AthenasJimenez** [comment] 2018-12-10 18:35
> I can confirm the issue is gone on 26730.

+1

**Closed as completed** 2018-12-10 18:37 UTC
